package daemon

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"strings"
	"time"

	qrcode "github.com/skip2/go-qrcode"
)

// ConnectionInfo holds the data encoded in QR codes for mobile connections.
type ConnectionInfo struct {
	Host  string `json:"host"`
	Port  int    `json:"port"`
	Token string `json:"token"`
}

// GenerateQRCode creates a QR code PNG containing connection info.
// The connection info is JSON-encoded and then base64-encoded for safe scanning.
func GenerateQRCode(host string, port int, token string, size int) ([]byte, error) {
	info := ConnectionInfo{
		Host:  host,
		Port:  port,
		Token: token,
	}
	data, err := json.Marshal(info)
	if err != nil {
		return nil, fmt.Errorf("marshal connection info: %w", err)
	}

	// Encode as base64 for safer QR scanning
	encoded := base64.StdEncoding.EncodeToString(data)

	png, err := qrcode.Encode(encoded, qrcode.Medium, size)
	if err != nil {
		return nil, fmt.Errorf("generate QR code: %w", err)
	}
	return png, nil
}

// GenerateQRCodeASCII creates an ASCII art QR code for terminal display.
func GenerateQRCodeASCII(host string, port int, token string) (string, error) {
	info := ConnectionInfo{
		Host:  host,
		Port:  port,
		Token: token,
	}
	data, err := json.Marshal(info)
	if err != nil {
		return "", fmt.Errorf("marshal connection info: %w", err)
	}

	// Encode as base64 for safer QR scanning
	encoded := base64.StdEncoding.EncodeToString(data)

	qr, err := qrcode.New(encoded, qrcode.Medium)
	if err != nil {
		return "", fmt.Errorf("generate QR code: %w", err)
	}

	return qr.ToSmallString(false), nil
}

// FetchPublicIP queries cloud metadata endpoints to discover the instance's
// public IPv4 address. Returns an empty string on non-cloud machines or if the
// metadata service is unavailable.
func FetchPublicIP() string {
	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get("http://169.254.169.254/latest/meta-data/public-ipv4")
	if err != nil {
		return ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return ""
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return ""
	}
	ip := strings.TrimSpace(string(body))
	if net.ParseIP(ip) == nil {
		return ""
	}
	return ip
}

// GetLocalIPs returns non-loopback IPv4 addresses for LAN connections.
func GetLocalIPs() []string {
	var ips []string
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return ips
	}
	for _, addr := range addrs {
		if ipnet, ok := addr.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
			if ipnet.IP.To4() != nil {
				ips = append(ips, ipnet.IP.String())
			}
		}
	}
	return ips
}

// DecodeConnectionInfo decodes a base64-encoded JSON connection info string.
// This is the format encoded in QR codes generated by GenerateQRCode.
func DecodeConnectionInfo(encoded string) (*ConnectionInfo, error) {
	data, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("decode base64: %w", err)
	}

	var info ConnectionInfo
	if err := json.Unmarshal(data, &info); err != nil {
		return nil, fmt.Errorf("unmarshal connection info: %w", err)
	}

	return &info, nil
}
